### PR TITLE
Fix autocomplete double selection and arrow navigation

### PR DESCRIPTION
**Pull request by kononenko-a-m**
Hey @mseemann I found some bugs in autocomplete feature, here is fix for them, can you please review changes, and if all is ok pull it? Thanks!

### CODE REVIEW

**Comment by kononenko-a-m** [comment]
hi @mseemann, sure, both features related to autocomplete feature.
1. Autoselection on blur event happens, but user actually clicked on item from the list. By itself issue can be noticed that for a moment autoselected value has been shown in select box, before actually clicked shown, but it's half of the problem. As for autocomplete feature list of items should be reset after 1 is selected, it lead to the case when user click on item from filtered list, change event triggered, list has been reset, and then it couldn't perform selection of clicked item. Fixed via avoiding autoselection on blur, if focus moved (and in our case it's can be triggered only by click) to one of the item from the list. Sorry, if it's sounds complicated, but it was really tricky bug, which blocked from normal usage of autocomplete feature.
2. Prevent setting value on navigation though list, using arrow down/up buttons, when autocomplete enabled. When you have filtered list, and press arrow down, it would normally select item, which is fine without autocomplete, but with autocomplete it lead to putting value in input field, which used for filtering, so after arrow down, you would see only one item, which has been filtered. Using this fix, you can easily navigate though list using arrow buttons when it's filtered.

**Comment by mseemann** [comment]
@kononenko-a-m can you check the following steps:

previous behavior
- focus the autoselect 
- type _f_
- arrow down
- enter 
=>_France_ is selected and is show in the input field

new behavior
- same steps as above
=>but  _f_ is show in the input field (but i think it should be _France_). if the field blured the value in the input field is _France_ - but it looks odd for the user because he didn't see the selected option.

**Comment by kononenko-a-m** [comment]
@mseemann it's actually what I've intended to do. One thing, I think on enter field should be blurred, and preselected become selected.

With autocomplete navigation through items should do kinda preselect (as selection would break filtering), you can notice it via the grey box. When focus has been lost, then last preselected value become selected. This approach helps to keep navigation via arrow buttons when you have a lot of items in the box. The case with "f" and "France" not the issue, as you have only one value in the box.

So yes, it's changed for autocomplete - navigation don't use selection approach, but more like preselected, and if something is preselected, from my pov it's nice to make it selected on blur. As the alternative would be disabled arrow navigation for select with autocomplete at all, but I just found arrow navigation extremely user-friendly. We might go with an extra option, which could disable arrow navigation (but personally don't think that it would be very useful).

@mseemann what do you think about it?

**Comment by mseemann** [comment]
@kononenko-a-m can you have a look to these changes to the autocomplete feature? thx.

**Comment by mseemann** [comment]
@kononenko-a-m it's your feature. but you should be aware that there might be some users of the autocomplete feature that disagree with you. from my view such a feature should behave like the native autocomplete for input fields in the browsers. the only thing we change should be the look and the fact that we provide the values for autocompletion. If you think your are done, let me know - I'm going to merge this then.

**Comment by kononenko-a-m** [comment]
@mseemann agree, that there might be different approaches. probably this should be customised with one more attribute, which would enable/disable autoselection on blur, let me introduce it.

**Comment by mseemann** [comment]
👍

**Comment by kononenko-a-m** [comment]
@mseemann I've extruded autoselection on blur to separate feature

**Comment by mseemann** [comment]
@kononenko-a-m thx. will have a look. will need some time... :(

**Comment by mseemann** [comment]
@kononenko-a-m I'm confused :/ i checked the demo: it looks like the mdl-select component with [autoselectOnBlur]="true" behaves like the previous behavior and the mdl-select component without the this options behaves like the new behavior. am i doing anything wrong?

**Comment by kononenko-a-m** [comment]
@mseemann from the very beginning autocomplete has been designed like [autoselectOnBlur]="true". I mean that from the very beginning it was forcing autoselection on blur. I added the possibility to customize this, so now this behaviour can be changed. If no autoselectOnBlur passed then when focus is moved to other element no selection performed.

So actually, [autoselectOnBlur]="true" is original behaviour, just with bugfixing for this.

**Comment by kononenko-a-m** [comment]
@mseemann ?

**Comment by mseemann** [comment]
I'd like to hear what @tb thinks about this...

**Comment by tb** [comment]
@kononenko-a-m @mseemann I think its great to add this "autoselectOnBlur" option but the selection on "press enter" should work on both cases, see http://g.recordit.co/tj5smF187Y.gif

**Comment by tb** [comment]
@kononenko-a-m @mseemann I am working on change based on this PR that will address my previosu comment and also will remove need for `(change)="resetAutcomplete()" (inputChange)="onAutocompleteChange($event)"`. I would like the options visibility to be updated instead similar to how we mark selected options. I am also detecting other issues like no support for Backspace. 

The main challenge for me atm is that there is a lot of places that should tigger query change and visbility update... and its all located inside the MdlSelectComponent which makes it really complex. I am thinking of extracting some kind of service that will manage the options state. If you have some feedback to this, ideas, insparations please share.

**Comment by tb** [comment]
@kononenko-a-m @mseemann I made new PR that was build on top of this PR, see https://github.com/mseemann/angular2-mdl-ext/pull/1012 The main change is that it skips the autoselectOnBlur in flavor of better Enter, ESc, Tab & "click out" support.

**Pull request closed without merging**
