### PR TITLE
Select component now respects disabled state of the form control

### PR DESCRIPTION
**Pull request by nikoTM**

### CODE REVIEW

**Comment by nikoTM** [comment]
@mseemann does it make sense to preserve Input decorated disable and keep the state in _disabled ? I don't think you can use both Input disabled and FormControl disable at the same time.

**Comment by mseemann** [comment]
i dont think it is a problem to have both ways to disable a form control. The user should know what he is doing.

Can you remove src/e2e-app/app/select/select.component.js and the *.map file from your commit/pr?

**Comment by nikoTM** [comment]
@mseemann didn't know how to amend properly, just pushed as a separate commit.

**Comment by mseemann** [comment]
LGTM!

**Comment by mseemann** [comment]
published as @angular2-mdl-ext/select:0.9.2

**Pull request merged**
