### PR TITLE
Placeholder Fix

### PR DESCRIPTION
**Pull request by ctdocken**
Fixes for #156. Also included @adasq's fix for #144 (I didn't see it in his branch).

### CODE REVIEW

**Comment by tb** [comment]
@ctdocken After this change I can not see "None" when it is selected in "ngModel with placeholder (no initial value) and floating label" example

**Comment by ctdocken** [comment]
This was by design. The original work (on #116) treated null values as null; my logic behind this was the following:

1. It matches the way mdl-textfield works with non-empty fields. The float label does not show up until the field has some sort of input in it.
2. If the desired effect for "None" is to display none, the developer can make the value any non-empty value ("None", "N/A", " ", etc. to get the desired effect). It would be impossible to do this otherwise.

I probably better explained my rationale here, but you can see my poorer explanation in the other issue #156.

**Comment by ctdocken** [comment]
I added better/more examples to the sample application to show the intended differences. Let me know if that clears it up.

**Comment by mseemann** [comment]
@tb can you check this? thx.

**Comment by tb** [comment]
Thanks for adding all the examples the covers all use cases I believe. Great work @ctdocken

**Pull request merged**
