### PR TITLE
fab menu component

### PR DESCRIPTION
**Pull request by leojpod**
Implementation of #808

### CODE REVIEW

**Comment by mseemann** [comment]
Hi thx a lot for your contribution! I have added your component to the build/test/dist pipeline. Maybe you can add some useful tests (for example make sure that alwaysShowTooltips always works). Let me know if you are done. Then I'm going to merge this and publish your component.

You can run `npm run test` to see the coverage report in _coverage/coverage-remap/index.html_)

**Comment by leojpod** [comment]
@mseemann Tests should be ready! 
Big thanks to @dadakoko!

**Comment by leojpod** [comment]
@mseemann have you got a chance to look at the code?

**Comment by mseemann** [comment]
@leojpod: sorry for the delay :( going to merge your fab-menu. if all goes well it will be published asap.

**Comment by mseemann** [comment]
@leojpod there is a debug error output during the tests. I'm trying to understand and fix whats wrong there - will need some more time :( may be you can have a look to on this output.

**Comment by leojpod** [comment]
Should be cleared now. 
I keep forgetting that I need to make a wrapper or use a service to print the events in the console ... :man_facepalming:

**Pull request merged**
