### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sebbi08**
Added Methode to load the scss files in an angular cli project

### CODE REVIEW

**Comment by mseemann** [comment]
hi. thx for your contribution. what is the benefit of your approach and not using the webpack special syntax?
```
@import '~@angular2-mdl-ext/popover/popover';
@import '~@angular2-mdl-ext/select/select';
```

**Comment by sebbi08** [comment]
i could not find a way to editthe webpack config since this is done completely by angular cli

**Comment by mseemann** [comment]
you don't need to change the webpack config. just add this:

@import '~@angular2-mdl-ext/popover/popover';
@import '~@angular2-mdl-ext/select/select';

to your styles.scss file. webpack knows that '~@angular2-mdl-ext' is located in the node_modules folder...

**Comment by sebbi08** [comment]
ok that would have worked too but since i am using less as css pre-processor i'd not like to create a styles.scss just for importing these two modules

**Comment by mseemann** [comment]
i don't know much about less. but https://github.com/webpack/less-loader seems to have the same possibility (see the Import section)

**Comment by sebbi08** [comment]
thats true but i cant import .scss/.css files into less

**Comment by sebbi08** [comment]
ok forgett it it is posible i just have so say i omittet the file ending and that it did not work

@import '@angular2-mdl-ext/popover/popover.css';
@import '@angular2-mdl-ext/select/select.css';

**Comment by mseemann** [comment]
never mind!

**Pull request closed without merging**
