### PR TITLE
add 0 and '0' value for select

### PR DESCRIPTION
**Pull request by ozknemoy**

### CODE REVIEW

**Comment by mseemann** [comment]
hi! thx a lot for your pr. can you add some tests? just to make sure that your changes will not be removed or the behavior changes unintended.

**Comment by ozknemoy** [comment]
added a couple of tests

**Comment by mseemann** [comment]
thx! can you rebase your branch to solve the merge conflicts?

**Comment by ozknemoy** [comment]
hm... not sure, but i don see changes in master

**Comment by mseemann** [comment]
sorry. but i can't merge this. there are too many conflicts with the master:( closing this pr. if you want you can create a new one.

**Pull request closed without merging**
