### PR TITLE
expansion panel

### PR DESCRIPTION
**Pull request by abdulqadir93**
Initial implementation for issue #35

### CODE REVIEW

**Comment by mseemann** [comment]
hi! thanks a lot for your great contribution! I think we have to do some additional setup to make sure you can run the test and this new component is deployable to npm. I can do this in your branch if you enable write access for me to this pull request. I have not done this before but here https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/ you'll find information how to grant access. Can you do that?

**Comment by abdulqadir93** [comment]
Hello. Sorry for the late response. I was on the move. 
The "allow edits from maintainers" options is already checked. You should be able to edit the pull request. Thanks.

**Comment by mseemann** [comment]
you should now be able to run yarn test to get the coverage report. also you can run yarn build:dist to check the resulting package that will be published to npm if you are ready with your implementation.

**Comment by abdulqadir93** [comment]
@mseemann I have added a few unit tests. Would you be publishing to npm? Sorry I'm new to the open source community. Not sure how it all works.

**Comment by mseemann** [comment]
this is my part 😀  will be done in a few minutes...

**Pull request merged**
