### PR TITLE
feat(popover): add ability to choose which direction to display to

### PR DESCRIPTION
**Pull request by Progdom**
Should display left, right, top, bottom,  topRight, topLeft, bottomRight, bottomLeft.

### CODE REVIEW

**Comment by Progdom** [comment]
closes #654

**Comment by Progdom** [comment]
I use visibility instead of display none so that I can grab the bounding rects off the element. Then toggle visibility.

**Comment by mseemann** [comment]
Hi. thx for you contribution. Please make sure that the tests are running. There are some typescript errors. Also it would be good to add some unit tests. And please check the demo-app - the popover is no longer bound to the event source element - see the attached screenshot. thx!
bildschirmfoto 2017-04-18 um 17 28 31

**Comment by Progdom** [comment]
There's this really interesting issue with that. The sidebar is causing the popover to move over. When you shrink the page down to the point that it no longer shows it works as intended. I've been trying to figure out why this is.

**Comment by Progdom** [comment]
I've created a gitter room for this project. https://gitter.im/p-angular2-mdl-ext/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link You can talk to me on there.

**Comment by mseemann** [comment]
will have a look...

**Comment by Progdom** [comment]
So it looks like this won't be possible unless we make the popover a direct child of the document root. Otherwise it'll be relative to the move relative parent. We need to inject it at the body end, then do it based off the click event to make it relative to that coordinate.

**Comment by mseemann** [comment]
@Progdom sorry for the late response. there is already a concept for such usecases. pls have a look at the dialog in @angular-mdl/core. there the <dialog-outlet/> element is used to position elements globally. the user can decide where to put this component.

**Comment by mseemann** [comment]
closing this pr beecause there is no wor on it for a long period of time...

**Pull request closed without merging**
